In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print("Rows:", a.shape[0])
print("Columns:", a.shape[1])
print("Data Type:", a.dtype)

Rows: 2
Columns: 3
Data Type: int64


In [2]:
import numpy as np

print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np

a = np.array([10,20,30,40,50])

print(a[2])

30


In [5]:
import numpy as np

a = np.array([10,20,30,40,50])

print(a[1:4])

[20 30 40]


In [6]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[0:2,1:3])

[[2 3]
 [5 6]]


In [7]:
import numpy as np

a = np.array([4,9,16,25])

print(np.sqrt(a))

[2. 3. 4. 5.]


In [8]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a+b)
print("Subtraction:", a-b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]


In [9]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("Transpose:")
print(a.T)

print("Matrix Multiplication:")
print(np.dot(a,b))

Transpose:
[[1 3]
 [2 4]]
Matrix Multiplication:
[[19 22]
 [43 50]]


In [10]:
import numpy as np

a = np.array([10,20,30,40,50])

print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard Deviation:", np.std(a))
print("Variance:", np.var(a))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
